forMetadataRetrieve/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

forMetadataRetrieve/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Of Cars In Stock</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/OpportunityProductsSelector.cls
/**
 * Created by vpelykh on 19.01.2022.
 */

public with sharing class OpportunityProductsSelector {

    public static Id getAccountId(String name) {
        return [SELECT Id
                FROM Account
                WHERE Name = :name
                LIMIT 1
        ].Id;
    }

    public static List<OpportunityLineItem> selectOpportunityProductsForOpportunity(Id opportunityId) {
        return [
                SELECT Id,
                        Product2.Name,
                        Product2.Total_Amount__c,
                        Quantity
                FROM OpportunityLineItem
                WHERE OpportunityId = :opportunityId
        ];
    }

    public static Opportunity getOpportunityContact(Id opportunityId) {
        return [SELECT Id, Contact__c, Pricebook2Id
                FROM Opportunity
                WHERE Id = :opportunityId
        ];
    }

    public static List<OpportunityLineItem> selectOppProducts(List<Id> oppProductsIds) {
        return [
                SELECT Id,
                        Product2.Name,
                        Product2Id,
                        PricebookEntryId,
                        Quantity,
                        UnitPrice
                FROM OpportunityLineItem
                WHERE Id IN :oppProductsIds
        ];
    }
}